version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
